import * as XLSX from "xlsx";
import { getDocument } from "pdfjs-dist";

export const RECEIPT_FIELDS = ["id_agent", "no_struk", "date_trans", "subtotal", "service_charge", "discount", "dpp", "tax", "paid_amount", "total", "keterangan"] as const;
export type ReceiptField = typeof RECEIPT_FIELDS[number];
export type ReceiptRow = Record<ReceiptField, string> & { status: "NORMAL" | "DUPLIKAT"; sourceIndex: number };
export type ReceiptMapping = { field: ReceiptField; label: string; column: string; header: string };
export type ExcelPreview = { fileName: string; sheetNames: string[]; activeSheet: string; headerRow: number; totalColumns: number; totalRows: number; columnNames: string[]; previewRows: string[][]; mappings: ReceiptMapping[] };
export type ReceiptSummary = { count: number; unique: number; duplicate: number; duplicateGroups: number; subtotal: number; service_charge: number; discount: number; dpp: number; tax: number; paid_amount: number; total: number };
export type ReceiptParseResult = { rows: ReceiptRow[]; summary: ReceiptSummary; warning?: string; validation: string[]; excel?: ExcelPreview };

const emptyRow = (): Record<ReceiptField, string> => Object.fromEntries(RECEIPT_FIELDS.map((field) => [field, ""])) as Record<ReceiptField, string>;
const clean = (value: unknown) => value == null ? "" : String(value).trim();
const normalizeHeader = (value: unknown) => clean(value).toLowerCase().normalize("NFKD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, "");
const aliases: Record<ReceiptField, string[]> = { id_agent: ["id_agent", "agent_id", "idagent", "agent"], no_struk: ["no_struk", "nomor_struk", "no_receipt", "receipt_no", "receipt_number", "nomor_transaksi", "no_transaksi", "transaction_no", "order_no", "orderno"], date_trans: ["date_trans", "tanggal_transaksi", "tanggal", "date", "transaction_date", "order_time", "ordertime"], subtotal: ["subtotal", "sub_total"], service_charge: ["service_charge", "servicecharge", "biaya_layanan", "service_fee"], discount: ["discount", "diskon"], dpp: ["dpp", "dasar_pengenaan_pajak"], tax: ["tax", "pajak", "ppn", "tax_amount"], paid_amount: ["paid_amount", "paidamount", "paid", "jumlah_dibayar", "nominal_dibayar", "amount_paid"], total: ["total", "grand_total", "total_amount"], keterangan: ["keterangan", "catatan", "description", "remark", "notes"] };
const fieldForHeader = (header: unknown, dayGrossTarget = false): ReceiptField | undefined => { const normalized = normalizeHeader(header); if (dayGrossTarget && normalized === "day_gros") return "subtotal"; if (dayGrossTarget && normalized === "subtotal") return undefined; return RECEIPT_FIELDS.find((field) => aliases[field].includes(normalized)); };
const columnName = (index: number) => { let n = index + 1; let result = ""; while (n) { const remainder = (n - 1) % 26; result = String.fromCharCode(65 + remainder) + result; n = Math.floor((n - 1) / 26); } return result; };
export function parseIndonesianNumber(value: unknown): number { if (typeof value === "number") return Number.isFinite(value) ? value : 0; let text = clean(value).replace(/rp\.?/gi, "").replace(/\s/g, ""); if (!text) return 0; const negative = text.startsWith("-"); text = text.replace(/[^0-9,.]/g, ""); if (!text) return 0; const comma = text.lastIndexOf(","), dot = text.lastIndexOf("."); if (comma >= 0 && dot >= 0) text = comma > dot ? text.replace(/\./g, "").replace(",", ".") : text.replace(/,/g, ""); else if (comma >= 0) text = text.length - comma - 1 <= 2 ? text.replace(",", ".") : text.replace(/,/g, ""); else if (dot >= 0 && text.length - dot - 1 > 2) text = text.replace(/\./g, ""); const result = Number(text); return Number.isFinite(result) ? (negative ? -result : result) : 0; }
function normalizeDate(value: unknown): string { if (typeof value === "number") { const date = XLSX.SSF.parse_date_code(value); if (date) return `${date.y}-${String(date.m).padStart(2, "0")}-${String(date.d).padStart(2, "0")}`; } const text = clean(value); const iso = text.match(/(\d{4})[-/]([01]?\d)[-/]([0-3]?\d)/); if (iso) return `${iso[1]}-${iso[2].padStart(2, "0")}-${iso[3].padStart(2, "0")}`; const local = text.match(/([0-3]?\d)[-/]([01]?\d)[-/](\d{4})/); return local ? `${local[3]}-${local[2].padStart(2, "0")}-${local[1].padStart(2, "0")}` : text; }
function locateHeader(matrix: unknown[][], dayGrossTarget = false) { let best = -1, bestCount = 0; matrix.slice(0, 30).forEach((row, index) => { const count = row.filter((cell) => fieldForHeader(cell, dayGrossTarget)).length; if (count > bestCount) { best = index; bestCount = count; } }); return { index: best, count: bestCount }; }
function mappingsFor(matrix: unknown[][], headerIndex: number, dayGrossTarget = false): ReceiptMapping[] { const row = matrix[headerIndex] ?? []; return RECEIPT_FIELDS.flatMap((field) => { const index = row.findIndex((cell) => fieldForHeader(cell, dayGrossTarget) === field); return index < 0 ? [] : [{ field, label: field === "tax" ? "Pajak" : field === "no_struk" ? "No Struk" : field.replace(/_/g, " "), column: columnName(index), header: clean(row[index]) }]; }); }
function normalizeRows(matrix: unknown[][], headerIndex: number, mappings: ReceiptMapping[]): ReceiptRow[] { const indexByField = Object.fromEntries(mappings.map((m) => [m.field, m.column])) as Record<string, string>; const colIndex = (column: string) => { let n = 0; for (const char of column) n = n * 26 + char.charCodeAt(0) - 64; return n - 1; }; const rows: ReceiptRow[] = matrix.slice(headerIndex + 1).map((values, sourceIndex) => { const row = emptyRow(); for (const field of RECEIPT_FIELDS) { const mapping = indexByField[field]; const value = mapping ? values[colIndex(mapping)] : ""; row[field] = field === "date_trans" ? normalizeDate(value) : clean(value); } return { ...row, status: "NORMAL" as "NORMAL" | "DUPLIKAT", sourceIndex: sourceIndex + headerIndex + 1 }; }).filter((row) => { const values = RECEIPT_FIELDS.map((field) => row[field]); const text = values.join(" ").toLowerCase(); return values.some(Boolean) && !/^(total|grand total|subtotal|day_gros|footer|jumlah)\b/.test(text) && Boolean(row.no_struk || row.id_agent || row.date_trans || row.subtotal || row.tax || row.total); }); const counts = new Map<string, number>(); rows.forEach((row) => { if (row.no_struk) counts.set(row.no_struk, (counts.get(row.no_struk) ?? 0) + 1); }); rows.forEach((row) => { if (row.no_struk && (counts.get(row.no_struk) ?? 0) > 1) row.status = "DUPLIKAT"; }); return rows; }
export function summarizeReceiptRows(rows: ReceiptRow[]): ReceiptSummary { const duplicateRows = rows.filter((row) => row.status === "DUPLIKAT").length; const groups = new Set(rows.filter((row) => row.status === "DUPLIKAT").map((row) => row.no_struk)); const sum = (field: ReceiptField) => rows.reduce((total, row) => total + parseIndonesianNumber(row[field]), 0); const hasPaidAmount = rows.some((row) => row.paid_amount !== ""); const paidAmount = sum("paid_amount"); return { count: rows.length, unique: rows.length - duplicateRows, duplicate: duplicateRows, duplicateGroups: groups.size, subtotal: sum("subtotal"), service_charge: sum("service_charge"), discount: sum("discount"), dpp: sum("dpp"), tax: sum("tax"), paid_amount: paidAmount, total: hasPaidAmount ? paidAmount : sum("total") }; }
export function parseReceiptMatrix(matrix: unknown[][], excel?: ExcelPreview, dayGrossTarget = false): ReceiptParseResult { const header = locateHeader(matrix, dayGrossTarget); const mappings = header.index >= 0 ? mappingsFor(matrix, header.index, dayGrossTarget) : []; const rows = header.index >= 0 ? normalizeRows(matrix, header.index, mappings) : []; const hasPaidAmount = mappings.some((m) => m.field === "paid_amount"); const validation = ["File berhasil dibaca", ...(header.index >= 0 ? ["Header ditemukan"] : []), ...(mappings.some((m) => m.field === "no_struk") ? ["Kolom transaksi ditemukan"] : []), ...(mappings.some((m) => m.field === "subtotal") ? [dayGrossTarget ? "Kolom Day-Gros ditemukan" : "Kolom subtotal ditemukan"] : []), ...(mappings.some((m) => m.field === "tax") ? ["Kolom pajak ditemukan"] : []), ...(hasPaidAmount ? ["Kolom Paid Amount ditemukan — Total dihitung dari Paid Amount"] : []), ...(rows.length ? ["Data transaksi berhasil diproses"] : [])]; const missing = [!mappings.some((m) => m.field === "subtotal") ? (dayGrossTarget ? "Kolom Day-Gros tidak ditemukan pada file." : "Kolom subtotal tidak ditemukan pada file.") : "", !mappings.some((m) => m.field === "tax") ? "Kolom pajak tidak ditemukan pada file." : ""].filter(Boolean); return { rows, summary: summarizeReceiptRows(rows), validation, excel: excel ? { ...excel, mappings } : undefined, warning: missing.join(" ") || (!rows.length ? "Tidak ditemukan baris transaksi yang valid." : undefined) }; }
export function parseReceiptCsv(text: string): ReceiptParseResult { const first = text.split(/\r?\n/).find((line) => line.trim()) ?? ""; const delimiter = (first.match(/;/g)?.length ?? 0) > (first.match(/,/g)?.length ?? 0) ? ";" : ","; const matrix = text.split(/\r?\n/).filter((line) => line.trim()).map((line) => { const cells: string[] = []; let current = "", quoted = false; for (const char of line) { if (char === '"') quoted = !quoted; else if (char === delimiter && !quoted) { cells.push(current.trim()); current = ""; } else current += char; } cells.push(current.trim()); return cells; }); return parseReceiptMatrix(matrix); }
export async function parseReceiptFile(file: File, options: { dayGrossTarget?: boolean } = {}): Promise<ReceiptParseResult> { const extension = file.name.toLowerCase().split(".").pop(); if (extension === "csv") return parseReceiptCsv(await file.text()); if (extension === "xlsx" || extension === "xls") { const workbook = XLSX.read(await file.arrayBuffer(), { type: "array", cellDates: true }); const sheetName = workbook.SheetNames[0]; const sheet = workbook.Sheets[sheetName]; const matrix = XLSX.utils.sheet_to_json(sheet, { header: 1, raw: true, defval: "" }) as unknown[][]; const header = locateHeader(matrix, options.dayGrossTarget); const totalColumns = matrix.reduce((max, row) => Math.max(max, row.length), 0); const excel: ExcelPreview = { fileName: file.name, sheetNames: workbook.SheetNames, activeSheet: sheetName, headerRow: header.index + 1, totalColumns, totalRows: Math.max(0, matrix.length - Math.max(0, header.index + 1)), columnNames: Array.from({ length: totalColumns }, (_, index) => columnName(index)), previewRows: matrix.slice(0, Math.min(matrix.length, 16)).map((row) => row.map(clean)), mappings: [] }; return parseReceiptMatrix(matrix, excel, options.dayGrossTarget); } if (extension === "pdf") { const pdf = await getDocument({ data: new Uint8Array(await file.arrayBuffer()), useWorkerFetch: false }).promise; const lines: string[] = []; for (let pageNo = 1; pageNo <= pdf.numPages; pageNo++) { const page = await pdf.getPage(pageNo), content = await page.getTextContent(); lines.push(content.items.map((item) => ("str" in item ? item.str : "")).join(" ")); } const text = lines.join("\n"); if (!text.trim()) return { rows: [], summary: summarizeReceiptRows([]), validation: [], warning: "PDF merupakan scan/image tanpa text layer, sehingga data tidak dapat diekstrak secara normal." }; return parseReceiptCsv(text.replace(/\s{2,}/g, ",")); } return { rows: [], summary: summarizeReceiptRows([]), validation: [], warning: "Format file tidak didukung." }; }
export function receiptToCsv(rows: ReceiptRow[]): string { const headers = [...RECEIPT_FIELDS, "status"]; const escape = (v: string) => `"${v.replace(/"/g, '""')}"`; return [headers.join(","), ...rows.map((row) => headers.map((field) => escape(row[field as keyof ReceiptRow] as string)).join(","))].join("\n"); }
export const formatReceiptRupiah = (value: number) => new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", maximumFractionDigits: 0 }).format(value);
