import { useMemo, useRef, useState, type ChangeEvent, type DragEvent } from "react";
import { AlertTriangle, ArrowLeft, BarChart3, Check, Download, FileJson, Filter, Search, ShieldCheck, Trash2, Upload, X } from "lucide-react";
import { calculateForeSummary, formatForeRupiah, foreToCsv, parseForeJson, type ForeTransaction } from "@/lib/foreParser";
import { MAX_FILE_SIZE_BYTES } from "@/lib/transactionParser";

type Props = { onBack: () => void };
export default function ForeChecker({ onBack }: Props) {
  const [text, setText] = useState(""); const [source, setSource] = useState(""); const [rows, setRows] = useState<ForeTransaction[]>([]); const [notice, setNotice] = useState(""); const [query, setQuery] = useState(""); const [date, setDate] = useState(""); const [drag, setDrag] = useState(false); const fileRef = useRef<HTMLInputElement>(null);
  const analyze = (value = text) => { const result = parseForeJson(value); setRows(result.validTransactions); setNotice(result.error || (result.issues.length ? `${result.issues.length} baris tidak diproses karena format FORE tidak lengkap.` : `${result.validTransactions.length} transaksi FORE siap diperiksa.`)); };
  const loadFile = async (file?: File) => { if (!file) return; if (!file.name.toLowerCase().endsWith(".json") || file.size > MAX_FILE_SIZE_BYTES) { setNotice("Hanya file JSON maksimal 5 MB yang dapat diproses."); return; } const value = await file.text(); setText(value); setSource(file.name); analyze(value); };
  const filtered = useMemo(() => { const q = query.toLowerCase().trim(); return rows.filter((row) => (!q || [row.counterName, row.counterId, row.billingId, row.dateTime].some((value) => value.toLowerCase().includes(q))) && (!date || row.dateTime.slice(0, 10) === date)); }, [date, query, rows]);
  const summary = calculateForeSummary(filtered);
  const clear = () => { setText(""); setSource(""); setRows([]); setNotice(""); setQuery(""); setDate(""); };
  const exportCsv = () => { const url = URL.createObjectURL(new Blob([foreToCsv(filtered)], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = `nstax-fore-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); };
  return <div className="app-shell"><aside className="app-sidebar"><div className="brand-lockup"><div className="brand-mark"><span>α</span></div><div><div className="brand-name">nstax</div><div className="brand-caption">transaction intelligence</div></div></div><div className="sidebar-divider" /><nav className="sidebar-nav"><button className="nav-item" type="button" onClick={onBack}><ArrowLeft size={18} /><span>Kembali pilih mode</span></button><div className="nav-item is-active"><BarChart3 size={18} /><span>FORE Analysis</span></div></nav><div className="sidebar-footer"><div className="privacy-badge"><ShieldCheck size={16} /><div><strong>Local-first</strong><span>Data tidak keluar dari browser</span></div></div><div className="version-label">nstax / FORE</div></div></aside>
    <main className="main-content"><header className="topbar"><button className="button button-secondary compact" type="button" onClick={onBack}><ArrowLeft size={15} /> Kembali</button><div className="breadcrumb"><span>Workspace</span><span>›</span><strong>FORE Tax Checker</strong></div><div className="status-chip"><span className="status-dot" /></div></header><div className="page-container"><section className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> FORE TAX CHECKER</div><h1>Periksa transaksi<br /><em>FORE dengan presisi.</em></h1><p>Gunakan field FORE aktual: counter, billing, total, dan pajak. Parser FORE terpisah dari parser NSC.</p></div><div className="heading-meta"><span className="meta-label">CURRENT SOURCE</span><strong>{source || "Input JSON langsung"}</strong><span className="meta-subtitle">{rows.length ? `${rows.length} transaksi valid` : "Belum ada data dianalisis"}</span></div></section>
      <section className="input-panel panel-surface"><div className="panel-heading"><div className="panel-title-wrap"><span className="section-number">01</span><div><h2>Input data JSON FORE</h2><p>Upload file atau tempel payload FORE langsung.</p></div></div>{source && <span className="file-pill"><FileJson size={15} />{source}</span>}</div><div className="input-grid"><div className={`drop-zone ${drag ? "is-dragging" : ""}`} onDragEnter={(e) => { e.preventDefault(); setDrag(true); }} onDragOver={(e) => e.preventDefault()} onDragLeave={() => setDrag(false)} onDrop={(e: DragEvent<HTMLDivElement>) => { e.preventDefault(); setDrag(false); void loadFile(e.dataTransfer.files?.[0]); }}><div className="upload-symbol"><Upload size={20} /></div><strong>Tarik file JSON FORE ke sini</strong><span>atau pilih dari perangkat Anda</span><button className="button button-secondary" type="button" onClick={() => fileRef.current?.click()}><FileJson size={16} /> Pilih file JSON</button><small>Maksimal 5 MB · hanya .json</small><input ref={fileRef} type="file" accept=".json,application/json" hidden onChange={(e: ChangeEvent<HTMLInputElement>) => void loadFile(e.target.files?.[0])} /></div><div className="editor-wrap"><div className="editor-toolbar"><span className="editor-label">fore-payload.json</span><span className="editor-hint">UTF-8</span></div><textarea className="json-editor" value={text} onChange={(e) => { setText(e.target.value); setNotice(""); }} placeholder={'{\n  "tgl": "2026-08-01T03:42:04.000Z",\n  "counter_id": 480,\n  "billing_id": "260824800017",\n  "total": 29000,\n  "pajak": 2636\n}'} spellCheck={false} aria-label="Input JSON FORE" /></div></div><div className="input-actions"><div className="privacy-note"><ShieldCheck size={15} /> Diproses lokal di browser</div><div className="button-row"><button className="button button-ghost" type="button" onClick={clear}><Trash2 size={16} /> Clear</button><button className="button button-primary" type="button" onClick={() => analyze()}><BarChart3 size={16} /> Analisis FORE</button></div></div></section>
      {notice && <div className={`notice ${rows.length ? "notice-success" : "notice-error"}`}><span className="notice-icon">{rows.length ? <Check size={17} /> : <AlertTriangle size={17} />}</span>{notice}</div>}
      {rows.length > 0 && <><section className="analysis-section"><div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> 02 · FORE OUTPUT</div><h2>Ringkasan FORE</h2></div></div><div className="metric-grid"><div className="metric-card"><span className="metric-label">Total transaksi</span><strong className="metric-value">{summary.count.toLocaleString("id-ID")}</strong><span className="metric-helper">baris valid</span></div><div className="metric-card"><span className="metric-label">Total total</span><strong className="metric-value">{formatForeRupiah(summary.total)}</strong><span className="metric-helper">SUM(total)</span></div><div className="metric-card"><span className="metric-label">Total pajak</span><strong className="metric-value">{formatForeRupiah(summary.pajak)}</strong><span className="metric-helper">SUM(pajak)</span></div><div className="metric-card"><span className="metric-label">Counter unik</span><strong className="metric-value">{summary.uniqueCounters.toLocaleString("id-ID")}</strong><span className="metric-helper">COUNT UNIQUE(counter_id)</span></div></div></section><section className="table-section"><div className="section-heading table-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> 03 · FORE REGISTER</div><h2>Daftar transaksi FORE</h2></div><button className="button button-secondary compact" type="button" onClick={exportCsv}><Download size={15} /> Export CSV</button></div><div className="filters-bar"><div className="search-field"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari counter, billing ID..." /></div><label className="date-field"><Filter size={15} /><span>Tanggal</span><input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label></div><div className="table-shell"><table><thead><tr><th>No</th><th>Tanggal</th><th>Counter</th><th>Billing ID</th><th className="numeric">Total</th><th className="numeric">Pajak</th></tr></thead><tbody>{filtered.map((row, index) => <tr key={row.id}><td>{String(index + 1).padStart(2, "0")}</td><td>{row.dateTime}</td><td><strong>{row.counterName}</strong><br /><small>{row.counterId}</small></td><td>{row.billingId}</td><td className="numeric">{formatForeRupiah(row.total)}</td><td className="numeric">{formatForeRupiah(row.pajak)}</td></tr>)}</tbody></table></div></section></>}
    </div></main></div>;
}
