import { useMemo, useRef, useState, type ChangeEvent, type DragEvent } from "react";
import { ArrowLeft, Check, Download, FileSpreadsheet, FileText, Filter, Search, ShieldCheck, Trash2, Upload, AlertTriangle } from "lucide-react";
import { formatReceiptRupiah, parseIndonesianNumber, parseReceiptFile, receiptToCsv, type ReceiptRow, type ReceiptSummary, type ExcelPreview } from "@/lib/receiptParser";

type Props = { onBack: () => void };
const money = ["subtotal", "service_charge", "discount", "dpp", "tax", "paid_amount", "total"] as const;
const fields = ["id_agent", "no_struk", "date_trans", "subtotal", "service_charge", "discount", "dpp", "tax", "paid_amount", "total", "keterangan"];
const labels: Record<string, string> = { id_agent: "ID Agent", no_struk: "No Struk", date_trans: "Date Trans", subtotal: "Subtotal", service_charge: "Service Charge", discount: "Discount", dpp: "DPP", tax: "Tax", paid_amount: "Paid Amount", total: "Total", keterangan: "Keterangan" };
function Metric({ label, value, isMoney = true }: { label: string; value: number; isMoney?: boolean }) { return <div className="metric-card"><span className="metric-label">{label}</span><strong className="metric-value">{isMoney ? formatReceiptRupiah(value) : value.toLocaleString("id-ID")}</strong><span className="metric-helper">SUM dari file</span></div>; }
export function ExcelInfo({ excel, targetLabel = "Subtotal" }: { excel: ExcelPreview; targetLabel?: string }) { return <><div className="excel-meta"><div><span>Nama file</span><strong>{excel.fileName}</strong></div><div><span>Jumlah sheet</span><strong>{excel.sheetNames.length}</strong></div><div><span>Sheet aktif</span><strong>{excel.activeSheet}</strong></div><div><span>Jumlah kolom</span><strong>{excel.totalColumns.toLocaleString("id-ID")}</strong></div><div><span>Jumlah baris data</span><strong>{excel.totalRows.toLocaleString("id-ID")}</strong></div><div><span>Header terdeteksi</span><strong>Baris {excel.headerRow || "—"}</strong></div></div><div className="mapping-panel"><div className="eyebrow"><span className="eyebrow-line" /> HASIL PEMBACAAN EXCEL</div><div className="mapping-grid">{excel.mappings.filter((mapping) => ["no_struk", "subtotal", "tax", "paid_amount"].includes(mapping.field)).map((mapping) => <div key={mapping.field}><strong>{mapping.field === "tax" ? "Pajak" : mapping.field === "no_struk" ? "No Struk" : mapping.field === "paid_amount" ? "Paid Amount (sumber Total)" : targetLabel}</strong><span>Kolom: <b>{mapping.column}</b></span><span>Header: {mapping.header}</span></div>)}</div></div><div className="excel-preview"><div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> PREVIEW STRUKTUR EXCEL</div><h2>Seluruh kolom file</h2></div><span className="result-count">Preview {Math.max(0, excel.previewRows.length - excel.headerRow)} baris · perhitungan {excel.totalRows.toLocaleString("id-ID")} baris</span></div><div className="excel-scroll"><table className="excel-table"><thead><tr>{excel.columnNames.map((column, index) => <th key={column}><span>{column}</span><small>{excel.previewRows[excel.headerRow - 1]?.[index] || ""}</small></th>)}</tr></thead><tbody>{excel.previewRows.slice(excel.headerRow).map((row, rowIndex) => <tr key={rowIndex}>{excel.columnNames.map((column, index) => <td key={column}>{row[index] || ""}</td>)}</tr>)}</tbody></table></div></div></>; }
export default function ReceiptChecker({ onBack }: Props) {
  const [rows, setRows] = useState<ReceiptRow[]>([]); const [summary, setSummary] = useState<ReceiptSummary | null>(null); const [source, setSource] = useState(""); const [notice, setNotice] = useState(""); const [validation, setValidation] = useState<string[]>([]); const [excel, setExcel] = useState<ExcelPreview>(); const [query, setQuery] = useState(""); const [status, setStatus] = useState<"ALL" | "NORMAL" | "DUPLIKAT">("ALL"); const [drag, setDrag] = useState(false); const inputRef = useRef<HTMLInputElement>(null);
  const analyze = async (file?: File) => { if (!file) return; if (!/\.(pdf|xlsx?|csv)$/i.test(file.name)) { setNotice("Format tidak didukung. Pilih PDF, Excel (.xlsx/.xls), atau CSV."); return; } try { const result = await parseReceiptFile(file); setRows(result.rows); setSummary(result.summary); setSource(file.name); setValidation(result.validation); setExcel(result.excel); setNotice(result.warning || `${result.rows.length.toLocaleString("id-ID")} transaksi berhasil dibaca.`); } catch { setRows([]); setSummary(null); setExcel(undefined); setValidation([]); setNotice("File tidak dapat dibaca. Pastikan format dan struktur header sesuai."); } };
  const filtered = useMemo(() => { const q = query.toLowerCase().trim(); return rows.filter((row) => (!q || [row.id_agent, row.no_struk, row.date_trans, row.keterangan].some((v) => v.toLowerCase().includes(q))) && (status === "ALL" || row.status === status)); }, [query, rows, status]);
  const exportRows = (onlyDuplicate = false) => { const selected = onlyDuplicate ? rows.filter((row) => row.status === "DUPLIKAT") : filtered; const url = URL.createObjectURL(new Blob([receiptToCsv(selected)], { type: "text/csv;charset=utf-8" })); const link = document.createElement("a"); link.href = url; link.download = onlyDuplicate ? "nstax-duplicate-receipts.csv" : "nstax-receipts.csv"; link.click(); URL.revokeObjectURL(url); };
  const clear = () => { setRows([]); setSummary(null); setSource(""); setNotice(""); setValidation([]); setExcel(undefined); setQuery(""); setStatus("ALL"); };
  const renderCell = (row: ReceiptRow, field: string) => money.includes(field as typeof money[number]) ? formatReceiptRupiah(parseIndonesianNumber(row[field as keyof ReceiptRow])) : row[field as keyof ReceiptRow] || "—";
  return <div className="app-shell"><aside className="app-sidebar"><div className="brand-lockup"><div className="brand-mark"><span>α</span></div><div><div className="brand-name">nstax</div><div className="brand-caption">transaction intelligence</div></div></div><div className="sidebar-divider" /><nav className="sidebar-nav"><button className="nav-item" type="button" onClick={onBack}><ArrowLeft size={18} /><span>Kembali pilih mode</span></button><div className="nav-item is-active"><FileText size={18} /><span>CEK STRUK</span></div></nav><div className="sidebar-footer"><div className="privacy-badge"><ShieldCheck size={16} /><div><strong>Local-first</strong><span>Data tidak keluar dari browser</span></div></div><div className="version-label">nstax / CEK STRUK</div></div></aside>
    <main className="main-content"><header className="topbar"><button className="button button-secondary compact" type="button" onClick={onBack}><ArrowLeft size={15} /> Kembali</button><div className="breadcrumb"><span>Workspace</span><span>›</span><strong>CEK STRUK</strong></div><div className="status-chip"><span className="status-dot" /></div></header><div className="page-container"><section className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> CEK STRUK · RECEIPT AUDIT</div><h1>Baca struk<br /><em>dengan presisi.</em></h1><p>Upload PDF, Excel, atau CSV. Excel ditampilkan dengan seluruh struktur kolom sebelum perhitungan.</p></div><div className="heading-meta"><span className="meta-label">CURRENT SOURCE</span><strong>{source || "Belum ada file"}</strong><span className="meta-subtitle">{rows.length ? `${rows.length.toLocaleString("id-ID")} transaksi terbaca` : "Menunggu file"}</span></div></section>
      <section className="input-panel panel-surface"><div className="panel-heading"><div className="panel-title-wrap"><span className="section-number">01</span><div><h2>Upload file struk</h2><p>PDF, Excel, dan CSV dengan header field transaksi.</p></div></div>{source && <span className="file-pill"><FileText size={15} />{source}</span>}</div><div className={`drop-zone ${drag ? "is-dragging" : ""}`} onDragEnter={(e) => { e.preventDefault(); setDrag(true); }} onDragOver={(e) => e.preventDefault()} onDragLeave={() => setDrag(false)} onDrop={(e: DragEvent<HTMLDivElement>) => { e.preventDefault(); setDrag(false); void analyze(e.dataTransfer.files?.[0]); }}><div className="upload-symbol"><Upload size={20} /></div><strong>{drag ? "Lepaskan file di sini" : "Tarik file struk ke sini"}</strong><span>atau pilih dari perangkat Anda</span><button className="button button-secondary" type="button" onClick={() => inputRef.current?.click()}><FileSpreadsheet size={16} /> Pilih file</button><small>PDF · XLSX · XLS · CSV</small><input ref={inputRef} type="file" accept=".pdf,.xlsx,.xls,.csv,application/pdf" hidden onChange={(e: ChangeEvent<HTMLInputElement>) => { void analyze(e.target.files?.[0]); e.target.value = ""; }} /></div><div className="input-actions"><div className="privacy-note"><ShieldCheck size={15} /> Diproses lokal di browser</div><button className="button button-ghost" type="button" onClick={clear}><Trash2 size={16} /> Clear</button></div></section>
      {notice && <div className={`notice ${rows.length ? "notice-success" : "notice-error"}`}><span className="notice-icon">{rows.length ? <Check size={17} /> : <AlertTriangle size={17} />}</span>{notice}</div>}
      {validation.length > 0 && <div className="validation-panel">{validation.map((item) => <span key={item}><Check size={14} />{item}</span>)}</div>}
      {excel && <ExcelInfo excel={excel} />}
      {summary && <><section className="analysis-section"><div className="section-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> 02 · HASIL UTAMA</div><h2>Ringkasan pemeriksaan</h2></div></div><div className="metric-grid"><Metric label="Jumlah transaksi" value={summary.count} isMoney={false} /><Metric label="Total subtotal" value={summary.subtotal} /><Metric label="Total pajak" value={summary.tax} /><Metric label="Total (Paid Amount)" value={summary.total} /><Metric label="Duplikat" value={summary.duplicate} isMoney={false} /></div>{excel && <div className="used-columns">Kolom yang digunakan: {excel.mappings.filter((mapping) => ["no_struk", "subtotal", "tax", "paid_amount"].includes(mapping.field)).map((mapping) => <strong key={mapping.field}>{mapping.field === "tax" ? "Pajak" : mapping.field === "no_struk" ? "No Struk" : mapping.field === "paid_amount" ? "Paid Amount → Total" : "Subtotal"} → {mapping.column}</strong>)}</div>}</section><section className="table-section"><div className="section-heading table-heading"><div><div className="eyebrow"><span className="eyebrow-line" /> 03 · RECEIPT REGISTER</div><h2>Data transaksi</h2></div><div className="button-row"><button className="button button-secondary compact" type="button" onClick={() => exportRows(false)}><Download size={15} /> Export CSV</button><button className="button button-secondary compact" type="button" onClick={() => exportRows(true)}><Download size={15} /> Export Duplikat</button></div></div><div className="filters-bar"><div className="search-field"><Search size={16} /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Cari ID agent, no struk, tanggal, keterangan..." /></div><label className="date-field"><Filter size={15} /><span>Status</span><select value={status} onChange={(e) => setStatus(e.target.value as typeof status)}><option value="ALL">Semua</option><option value="NORMAL">Normal</option><option value="DUPLIKAT">Duplikat</option></select></label></div><div className="table-shell"><table><thead><tr><th>No</th>{fields.map((field) => <th key={field} className={money.includes(field as typeof money[number]) ? "numeric" : ""}>{labels[field]}</th>)}<th>Status</th></tr></thead><tbody>{filtered.map((row, index) => <tr key={`${row.sourceIndex}-${row.no_struk}`}><td>{String(index + 1).padStart(2, "0")}</td>{fields.map((field) => <td key={field} className={money.includes(field as typeof money[number]) ? "numeric" : ""}>{renderCell(row, field)}</td>)}<td><span className={`receipt-status ${row.status === "DUPLIKAT" ? "is-duplicate" : ""}`}>{row.status}</span></td></tr>)}</tbody></table></div><div className="table-footer">Menampilkan {filtered.length.toLocaleString("id-ID")} dari {rows.length.toLocaleString("id-ID")} transaksi</div></section></>}
    </div></main></div>;
}
